/* ====================================================== */
/* JAVASCRIPT LOGIC - ati-script.js                       */
/* ====================================================== */
(function() {
    let playerVideos = []; let currentVideoIndex = 0; let messages = {};
    const videoPlayerModalEl = document.getElementById("player3_videoPlayerModal");
    const videoPlayerMainAreaEl = document.getElementById("player3_videoPlayerMainArea");
    const videoModalTitleEl = document.getElementById("player3_videoModalTitle");
    const videoDropdownMenuEl = document.getElementById("videoDropdownMenu");
    let autoOpenTimer = null; let isAutoOpenCancelled = false; const COUNTDOWN_SECONDS = 5;
    function getMessage(key) { return messages[key] || `[${key}]`; }
    function parseData() { const dataContainer = document.getElementById('player3_data'); if (!dataContainer) return; const msgContainer = dataContainer.querySelector('#player3_messages'); if (msgContainer) { msgContainer.querySelectorAll('span').forEach(span => { messages[span.dataset.msg] = span.textContent; }); } dataContainer.querySelectorAll('div[data-platform]').forEach(platformDiv => { const platform = platformDiv.dataset.platform; const embedUrl = platformDiv.dataset.embedUrl; platformDiv.querySelectorAll('i').forEach(videoEl => { playerVideos.push({ platform: platform, id: videoEl.dataset.id, title: videoEl.dataset.title || 'Untitled Video', embedUrl: embedUrl }); }); }); }
    function renderVideoDropdownMenu() { if (!videoDropdownMenuEl) return; videoDropdownMenuEl.innerHTML = ''; if (playerVideos.length === 0) return; playerVideos.forEach((video, index) => { const listItem = document.createElement('div'); listItem.className = 'video-dropdown-item'; listItem.textContent = video.title; listItem.title = video.title; listItem.onclick = () => { loadVideoInModal(index, true); videoDropdownMenuEl.classList.remove('open'); }; videoDropdownMenuEl.appendChild(listItem); }); }
    function loadVideoInModal(index, autoplay = true) { currentVideoIndex = index; const video = playerVideos[index]; if (!video || !videoPlayerMainAreaEl) return; if (videoModalTitleEl) videoModalTitleEl.textContent = video.title; if (videoDropdownMenuEl) { Array.from(videoDropdownMenuEl.children).forEach((item, idx) => { item.classList.toggle('active-video-item', idx === index); }); } const existingVideo = videoPlayerMainAreaEl.querySelector('iframe, video, .player-message'); if (existingVideo) existingVideo.remove(); let newElement; const allowPolicy = "autoplay; fullscreen; picture-in-picture; encrypted-media"; const autoplayParam = autoplay ? 1 : 0; switch (video.platform) { case 'youtube': newElement = document.createElement('iframe'); newElement.src = `${video.embedUrl}${video.id}?autoplay=${autoplayParam}&mute=0&rel=0&modestbranding=1&iv_load_policy=3`; newElement.setAttribute('allow', allowPolicy); break; case 'archive': newElement = document.createElement('iframe'); newElement.src = `${video.embedUrl}${video.id}&autoplay=${autoplayParam}`; newElement.setAttribute('allow', allowPolicy); break; case 'dailymotion': newElement = document.createElement('iframe'); newElement.src = `${video.embedUrl}${video.id}?autoplay=${autoplayParam}&mute=0`; newElement.setAttribute('allow', allowPolicy); break; default: newElement = document.createElement('div'); newElement.className = 'player-message'; newElement.style.cssText = 'color: #ff8a80; display: flex; align-items: center; justify-content: center; height: 100%;'; newElement.textContent = getMessage('unsupported_video'); break; } if (newElement.tagName === 'IFRAME') { newElement.setAttribute('frameborder', '0'); newElement.setAttribute('allowfullscreen', ''); } videoPlayerMainAreaEl.prepend(newElement); }
    window.player3_slideVideoInModal = (direction) => { if(playerVideos.length === 0) return; const newIndex = (currentVideoIndex + direction + playerVideos.length) % playerVideos.length; loadVideoInModal(newIndex, true); }
    window.player3_toggleVideoDropdown = () => { if (videoDropdownMenuEl) { videoDropdownMenuEl.classList.toggle('open'); } }
    window.player3_openVideoPlayerModal = (startIndex = 0) => { if (!videoPlayerModalEl) return; if (playerVideos.length === 0) { clearTimeout(autoOpenTimer); hideTimerOverlay(); alert(getMessage('no_videos')); return; } videoPlayerModalEl.style.display = "block"; document.body.style.overflow = 'hidden'; renderVideoDropdownMenu(); loadVideoInModal(startIndex, true); }
    window.player3_closeVideoPlayerModal = () => { if(videoPlayerModalEl) videoPlayerModalEl.style.display = "none"; const existingVideo = videoPlayerMainAreaEl.querySelector('iframe, video, .player-message'); if (existingVideo) existingVideo.remove(); document.body.style.overflow = 'auto'; if (videoDropdownMenuEl) videoDropdownMenuEl.classList.remove('open'); }
    document.addEventListener("keydown", function(e){ if (videoPlayerModalEl && videoPlayerModalEl.style.display === "block") { if(e.key === "Escape") window.player3_closeVideoPlayerModal(); if(e.key === "ArrowRight") { e.preventDefault(); window.player3_slideVideoInModal(1); } if(e.key === "ArrowLeft") { e.preventDefault(); window.player3_slideVideoInModal(-1); } } });
    document.addEventListener('click', function(event) { const menuBtn = document.querySelector('.ati-video-player-menu-btn'); if (videoDropdownMenuEl && videoDropdownMenuEl.classList.contains('open')) { if (!videoDropdownMenuEl.contains(event.target) && !menuBtn.contains(event.target)) { videoDropdownMenuEl.classList.remove('open'); } } });
    const timerOverlayEl = document.getElementById('ati-timer-overlay-id');
    function hideTimerOverlay() { if (timerOverlayEl) { timerOverlayEl.style.display = 'none'; } }
    function cancelAutoOpen() { isAutoOpenCancelled = true; clearTimeout(autoOpenTimer); hideTimerOverlay(); }
    function startAutoOpenCountdown() { if (isAutoOpenCancelled || playerVideos.length === 0) return; if (timerOverlayEl) timerOverlayEl.style.display = 'flex'; autoOpenTimer = setTimeout(() => { if (!isAutoOpenCancelled) { hideTimerOverlay(); window.player3_openVideoPlayerModal(); } }, COUNTDOWN_SECONDS * 1000); }
    function initializeAutoOpenFeature() { const autoOpenBtn = document.getElementById('ati-auto-open-btn'); if (!autoOpenBtn) return; autoOpenBtn.addEventListener('click', function() { if (isAutoOpenCancelled) { window.player3_openVideoPlayerModal(); } else { cancelAutoOpen(); window.player3_openVideoPlayerModal(); } }); autoOpenBtn.addEventListener('dblclick', function(e) { e.preventDefault(); if (!isAutoOpenCancelled) { cancelAutoOpen(); } }); startAutoOpenCountdown(); }
    parseData();
    document.addEventListener('DOMContentLoaded', initializeAutoOpenFeature);
})();
